
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package edu.unnoba.compiladores.compilador_unnoba_2023;

/** CUP generated class containing symbol constants. */
public class MiParserSym {
  /* terminals */
  public static final int DISPLAY = 34;
  public static final int STRING_LITERAL = 31;
  public static final int PARENTESIS_CIERRA = 7;
  public static final int OPERADOR_MENOR = 13;
  public static final int DOS_PUNTOS = 24;
  public static final int CONTINUE = 28;
  public static final int FILTER = 33;
  public static final int OPERADOR_MAYOR = 12;
  public static final int FOR = 19;
  public static final int OPERADOR_MAYOR_IGUAL = 15;
  public static final int CORCHETE_CIERRA = 22;
  public static final int OPERADOR_MULTI = 5;
  public static final int OPERADOR_DISTINTO = 11;
  public static final int CONST_FLOAT = 41;
  public static final int IF = 48;
  public static final int PUNTO_COMA = 25;
  public static final int EOF = 0;
  public static final int OPERADOR_MENOR_IGUAL = 14;
  public static final int INPUT_INT = 44;
  public static final int error = 1;
  public static final int COMA = 23;
  public static final int INPUT_BOOL = 46;
  public static final int OPERADOR_OR = 17;
  public static final int INT_TYPE = 29;
  public static final int OPERADOR_SUMA = 2;
  public static final int CONST_BOOL = 39;
  public static final int BREAK = 27;
  public static final int LLAVE_ABRE = 8;
  public static final int ASIGNACION = 43;
  public static final int OPERADOR_AND = 16;
  public static final int OPERADOR_NOT = 18;
  public static final int CORCHETE_ABRE = 21;
  public static final int GUION_BAJO = 47;
  public static final int END_PROGRAM_SECTION = 38;
  public static final int ELSE = 49;
  public static final int OPERADOR_DIV = 4;
  public static final int OPERADOR_RESTA = 3;
  public static final int THEN = 51;
  public static final int PROGRAM_SECTION = 37;
  public static final int END = 26;
  public static final int INPUT_FLOAT = 45;
  public static final int END_DECLARE_SECTION = 36;
  public static final int LLAVE_CIERRA = 9;
  public static final int OPERADOR_IGUAL = 10;
  public static final int FLOAT_TYPE = 30;
  public static final int ELIF = 50;
  public static final int VAR = 42;
  public static final int PARENTESIS_ABRE = 6;
  public static final int DO = 20;
  public static final int CONST_INT = 40;
  public static final int DECLARE_SECTION = 35;
  public static final int BOOLEAN_TYPE = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPERADOR_SUMA",
  "OPERADOR_RESTA",
  "OPERADOR_DIV",
  "OPERADOR_MULTI",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "OPERADOR_IGUAL",
  "OPERADOR_DISTINTO",
  "OPERADOR_MAYOR",
  "OPERADOR_MENOR",
  "OPERADOR_MENOR_IGUAL",
  "OPERADOR_MAYOR_IGUAL",
  "OPERADOR_AND",
  "OPERADOR_OR",
  "OPERADOR_NOT",
  "FOR",
  "DO",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "COMA",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "END",
  "BREAK",
  "CONTINUE",
  "INT_TYPE",
  "FLOAT_TYPE",
  "STRING_LITERAL",
  "BOOLEAN_TYPE",
  "FILTER",
  "DISPLAY",
  "DECLARE_SECTION",
  "END_DECLARE_SECTION",
  "PROGRAM_SECTION",
  "END_PROGRAM_SECTION",
  "CONST_BOOL",
  "CONST_INT",
  "CONST_FLOAT",
  "VAR",
  "ASIGNACION",
  "INPUT_INT",
  "INPUT_FLOAT",
  "INPUT_BOOL",
  "GUION_BAJO",
  "IF",
  "ELSE",
  "ELIF",
  "THEN"
  };
}

